include $(HOME)/project/cpp/transaction-dsl/shared/ut.mk

extra-srcs = sched/action/Procedure.cc \
             sched/action/Finally.cc \
             sched/action/NilFinalAction.cc \
             sched/action/LinkedSchedAction.cc \
             sched/action/SchedSequentialAction.cc \
             sched/action/SchedThrowAction.cc \
             sched/action/SchedVoidAction.cc \
             sched/action/SchedWaitAction.cc \
             sched/action/SchedSwitchCaseAction.cc \
             sched/action/SchedConcurrentAction.cc \
             sched/action/SchedWithIdAction.cc \
             sched/action/ActionThread.cc \
             sched/trans/SimpleRuntimeContextInfo.cc \
             sched/trans/SimpleTransactionInfo.cc \
             sched/trans/TransactionListenerProxy.cc \
             sched/trans/SimpleTransactionMode.cc \
             sched/trans/SchedTransaction.cc \
             sched/trans/BaseTransactionScheduler.cc \
             sched/trans/SimpleTransactionScheduler.cc \
             sched/trans/SimpleTransactionContext.cc   \
	     utils/ActionStatus.cc  \
             utils/AdaptedTimerInfo.cc  \
             utils/RuntimeContextAutoSwitch.cc \
             utils/SimpleRuntimeContext.cc \
             utils/StopCause.cc \
             ext/mutex/action/SchedLockAction.cc  \
             ext/mutex/impl/AbstractTransMutexScheduler.cc  \
             sched/trans/TransMutexSchedulerAdapter.cc 
          
             

include $(HOME)/project/cpp/transaction-dsl/shared/rules.mk
