include $(HOME)/project/cpp/trans-dsl/shared/ut.mk

extra-srcs = sched/action/Procedure.cc \
             sched/action/Finally.cc \
             sched/action/NilFinalAction.cc \
             sched/action/LinkedSchedAction.cc \
             sched/action/SchedSequentialAction.cc \
             sched/action/SchedThrowAction.cc \
             sched/action/SchedVoidAction.cc \
             sched/action/SchedWaitAction.cc \
             sched/action/SchedSwitchCaseAction.cc \
             sched/action/SchedConcurrentAction.cc \
             sched/action/SchedTimerProtAction.cc \
             sched/action/SchedLoopAction.cc \
             sched/action/ActionThread.cc \
             sched/action/SchedSafeModeAction.cc \
             sched/trans/SimpleRuntimeContextInfo.cc \
             sched/trans/SimpleTransactionInfo.cc \
             sched/trans/TransactionListenerProxy.cc \
             sched/trans/SimpleTransactionMode.cc \
             sched/trans/SchedTransaction.cc \
             sched/trans/BaseTransactionScheduler.cc \
             sched/trans/SimpleTransactionScheduler.cc \
             sched/trans/SimpleTransactionContext.cc \
             sched/action/SchedPeekAction.cc \
             sched/action/SchedExclusiveAction.cc \
             ext/multi-thread/action/SchedForkAction.cc \
             ext/multi-thread/action/SchedJoinAction.cc \
             ext/multi-thread/trans/MultiThreadScheduler.cc \
             ext/multi-thread/trans/MultiThreadTransactionScheduler.cc \
             utils/ActionStatus.cc  \
             utils/RelativeTimer.cc  \
             utils/RuntimeContextAutoSwitch.cc \
             utils/SimpleRuntimeContext.cc \
             utils/AdaptedTimerInfo.cc  \
             utils/StopCause.cc  \
             sched/port/PlatformSpecifiedRelativeTimer.cc  \
             ext/mutex/action/SchedLockAction.cc  \
             ext/mutex/impl/AbstractTransMutexScheduler.cc  \
             sched/trans/TransMutexSchedulerAdapter.cc 
             

include $(HOME)/project/cpp/trans-dsl/shared/rules.mk
